// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {openactions} from '../models';

export function GetRecentFolders():Promise<Array<main.Folder>>;

export function GetSoftwareList():Promise<Array<openactions.Software>>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function Open(arg1:string):Promise<void>;

export function OpenWith(arg1:string,arg2:number):Promise<void>;

export function Quit():Promise<void>;

export function Search(arg1:string):Promise<Array<main.Folder>>;
