// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {recentfolders} from '../models';

export function GetRecentFolders():Promise<Array<recentfolders.Entry>>;

export function Quit():Promise<void>;
