// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
