// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
