// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSoftware(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSoftware'](arg1, arg2, arg3);
}

export function DeleteSoftware(arg1) {
  return window['go']['main']['App']['DeleteSoftware'](arg1);
}

export function GetRecentFolders() {
  return window['go']['main']['App']['GetRecentFolders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSoftwareList() {
  return window['go']['main']['App']['GetSoftwareList']();
}

export function HideAfterOpen() {
  return window['go']['main']['App']['HideAfterOpen']();
}

export function IsDirectory(arg1) {
  return window['go']['main']['App']['IsDirectory'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenWith(arg1, arg2) {
  return window['go']['main']['App']['OpenWith'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Record(arg1) {
  return window['go']['main']['App']['Record'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function UpdateSoftware(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSoftware'](arg1, arg2, arg3, arg4);
}
